<?php

/**
 * @file
 * File containing ci_slide module.
 */

use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_theme().
 */
function ci_slide_theme($existing, $type, $theme, $path) {
  return [
    'node__slide' => [
      'base hook' => 'node',
    ],
    'paragraph__slide' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements theme_preprocess_paragraph__slide().
 */
function ci_slide_preprocess_paragraph__slide(array &$variables) {
  $paragraph = $variables['paragraph'];
  $src = '';
  if (!$paragraph->get('field_image')->isEmpty()) {
    $file = $paragraph->field_image->entity;
    if ($file) {
      $path = $file->getFileUri();
    }
    $img_style = ImageStyle::load('home_top_slider');
    if ($img_style !== NULL) {
      $src = $img_style->buildUrl($path);
    }
  }
  $variables['bg'] = [
    'src' => $src,
  ];
}
